import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '@fortawesome/fontawesome-svg-core/styles.css';
import { ThemeProvider } from './ThemeProvider';

import { config } from '@fortawesome/fontawesome-svg-core';
import Footer from '@/components/base/Footer';
import NavbarComponent from '@/components/base/Navbar';
config.autoAddCss = false;
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <ThemeProvider
                    attribute="class"
                    defaultTheme="system"
                    enableSystem
                >
                    <div className="flex min-h-screen flex-col ">
                        <div className="relative overflow-auto">
                            <NavbarComponent />
                        </div>
                        <main className="relative mt-[128px] flex-1 py-4">
                            {children}
                        </main>
                        <Footer />
                    </div>
                </ThemeProvider>
                {/* <Providers>
                    <div className="flex min-h-screen flex-col ">
                        <Navbar />
                        <div className="container flex-1 py-4">{children}</div>
                        <Footer />
                    </div>
                </Providers> */}
            </body>
        </html>
    );
}
